### PR TITLE
Task completion button added and confirmation also

### LINKED ISSUE #46: New task complete button and confirmation that the task has been completed
**Is your feature request related to a problem? Please describe.**
1) No task completion button available
2) After task completion no message to show, completed status

**Describe the solution you'd like**
1) A card showing "well done on completing" and a complete button

Screenshot
image

### PR DESCRIPTION
**Pull request by RohithNair27**
## Description

Added confirmation ui when completing task 

[screen-capture.webm](https://github.com/user-attachments/assets/ee918247-e97a-4881-8ba4-5ef4dcbda76c)

Fixes #46

## Type of change

Please delete options that are not relevant.

- [ /] New feature (non-breaking change)

## Checklist:

- [ /] My code follows the style guidelines of this project
- [ /] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ /] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bryans-go** [comment]
@RohithNair27 Please resolve conflicts before we test changes

**Review by bryans-go — CHANGES_REQUESTED** [review]
@RohithNair27 Please resolve conflicts before we test changes

**Comment by RohithNair27** [comment]
Oh ok, will do that

**Comment by RohithNair27** [comment]
Some issue with Lint, not recognizing the functions being used inside backticks. Due to which face the issue
I think somone else is working on it and have pull a request one's their's is done I will push mine again

**Comment by bryans-go** [comment]
@RohithNair27  these are steps to follow in order to pass all the checks. 
all the contributors should follow these else their PR will be closed
1.  go to your fork and click on sync fork and click Update Branch
2.  then go to the directory on your local machine
3. Run `git fetch origin`
4. Run `git pull origin main`
5. Then resolve the conflicts if any.
6. Then force push your branch by `git push origin branch-name -f`

**Pull request closed without merging**
