### PR TITLE
Enhance Todo List: Add 'Enter' Key Functionality for Task Addition and Editing

### LINKED ISSUE #18: Add "Enter Key" Functionality to Trigger Task Submission
Currently, tasks in the Todo-List application are only submitted when the "Add" button is clicked. To improve user experience, I propose adding functionality to submit tasks when the "Enter" key is pressed while focusing on the task name, date, or time input fields. This enhancement will allow users to quickly add tasks without needing to use the mouse or tap the button manually.

**Proposed Changes:**
Add event listeners to the task name, date, and time input fields.
Ensure that pressing the "Enter" key triggers the existing addTodo() function.

This improvement aligns with the goals of **Hacktoberfest**, and I'd like to **contribute** to this as part of the program. @Anshgrover23, please assign this issue to me and add the Hacktoberfest labels so I can work on it.

Thank you!

### PR DESCRIPTION
**Pull request by mudasirmurtaza**
This PR enhances the functionality of the Todo List application by adding support for triggering both task addition and task updates via the "Enter" key, improving the overall user experience. Previously, users had to manually click the "Add" or "Update" buttons to add or edit tasks. Now, pressing the "Enter" key while entering a task or editing an existing task will perform the corresponding action automatically. 

#### **Changes Made:**
- **Enter Key Functionality:**
  - Implemented key event listeners for the "Enter" key across the task input fields.
  - Users can now press "Enter" to:
    - Add a new task when not in edit mode.
    - Update an existing task when in edit mode.
  
- **Task Editing Workflow:**
  - Added a flag (`isEditing`) to track whether the user is in "add" or "edit" mode.
  - Stored the index of the task being edited (`editingIndex`) to ensure the correct task is updated.
  - Automatically switch between "Add" and "Update" buttons based on the current mode (task addition or editing).

- **UX Enhancement:**
  - The input fields are now more responsive, and task management is smoother.
  - Minor tweaks to the layout and styling were made for better consistency.

#### **Issue Link:**
Closes #18  – Add "Enter Key" Functionality to Trigger Task Submission

#### **Additional Notes:**
Please add the **Hacktoberfest** label to this PR as part of the Hacktoberfest initiative, so it can be counted towards contributions for participants.

### CODE REVIEW

**Comment by bryans-go** [comment]
@mudasirmurtaza Thanks for the effort. Please tend to resolve the conflicts before we do final test and merge it

**Review by bryans-go — CHANGES_REQUESTED** [review]
@mudasirmurtaza Thanks for the effort. Please tend to resolve the conflicts before we do final test and merge it

**Comment by mudasirmurtaza** [comment]
@bryans-go , I have resolved the conflict and checked that the enter button is working well.

Also, one small question that, you will be adding the labels to the PR as well, right? The labels doesn't get attached automatically.

**Comment by mudasirmurtaza** [comment]
@bryans-go, I have made a change which is working fine, why I am not able to pass the checks? Can we merge this without passing checks ?

**Comment by bryans-go** [comment]
@mudasirmurtaza  these are steps to follow in order to pass all the checks. 
all the contributors should follow these else their PR will be closed
1.  go to your fork and click on sync fork and click Update Branch
2.  then go to the directory on your local machine
3. Run `git fetch origin`
4. Run `git pull origin main`
5. Then resolve the conflicts if any.
6. Then force push your branch by `git push origin branch-name -f`

**Pull request closed without merging**
