### PR TITLE
changes have been made

### LINKED ISSUE #12: Changing the UI of a website and make it responsive
I will convert the UI into blue and black theme which denotes dedication and also make it responsive for the mobile phones.

### PR DESCRIPTION
**Pull request by Bhumika-00**
fixes #12 
the theme and transitons have been added

### CODE REVIEW

**Comment by Bhumika-00** [comment]
please review this

**Comment by bryans-go** [comment]
hey I think you need to test your changes and then ask for review 
image
I'm not able to set the time field

**Comment by bryans-go** [comment]
@Bhumika-00 
image
below the input fields there is empty box which was not initially there

**Review by bryans-go — CHANGES_REQUESTED** [review]
@Bhumika-00 
image
below the input fields there is empty box which was not initially there.
you can also improve it

**Comment by Bhumika-00** [comment]
Your list is looking like this
  VID_20241012_100856.mp4
<https://drive.google.com/file/d/1JzphQBNT8ijB103_1kuPqkavgIkS68Zs/view?usp=drivesdk>

**Comment by Bhumika-00** [comment]
Ok, no problem.

**Comment by Bhumika-00** [comment]
Can you please allow me to delete the repo actually there is issue with my
github desktop

**Comment by Bhumika-00** [comment]
Ok, I will do that.

**Pull request closed without merging**
