### PR TITLE
Fix: integrated a modern UI into the website, ensuring a clean and intuitive design for an improved UX

### LINKED ISSUE #48: [FEATURE] Making the UI more modern , with so many interactive effects
I want to make something like this 
I want to change the css and js to achieve this 
Screenshot 2024-10-12 at 9 34 22 AM

### PR DESCRIPTION
**Pull request by MOHIT-IITP**
## Description

Changed the ui of the site and add some icon to be more interactive 

Fixes #48 

Screenshot 2024-10-12 at 11 33 15 AM

- [ ] Bug fix (non-breaking change)
- [x] New feature (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so that they can be reproduced.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by bryans-go — CHANGES_REQUESTED** [review]
@MOHIT-IITP Please resolve conflicts before we test it

**Comment by MOHIT-IITP** [comment]
Bro i am facing issue when i am resolving the conflict and then merging , after that site is github is just reloading and realoading , i am trying again, from my side , if you have any solution then please help me

**Comment by bryans-go** [comment]
@MOHIT-IITP Please resolve conflicts and do the following.
1.  go to your fork and click on sync fork and click Update Branch
2.  then go to the directory on your local machine
3. Run `git fetch origin`
4. Run `git pull origin main`
5. Then resolve the conflicts if any.
6. Then force push your branch by `git push origin branch-name -f`

**Comment by MOHIT-IITP** [comment]
@bryans-go  can i work on another branch ( new) , so there will be no conflict .

**Comment by bryans-go** [comment]
@MOHIT-IITP just resolve the conflicts. We will handle everything else ourselves

**Pull request closed without merging**
